variables:
    PYTHON: python3.6

before_script:
  - yum install -y python36 python36-scipy python36-numpy python36-pandas python36-setuptools python36-pip
  - $PYTHON -m pip install --upgrade pip
  - $PYTHON -m pip install torch

pip-install:
    stage: install
    script:
      - $PYTHON -m pip install .

pytest:
    stage: test
    script:
      - $PYTHON setup.py pytest

stages:
  - install
  - test
