language: python
dist: xenial

os:
  - linux

python:
  - 3.5
  - 3.6
  - 3.7


addons:
  apt:
    packages:
      - python-setuptools
      - libhdf5-serial-dev
      - pandoc
      - python-pygments
      - python3-pygments
      - nodejs

script:
  python -m pip install torch
  python setup.py pytest
