language: python
dist: xenial

os:
  - linux

python:
  - 3.8


addons:
  apt:
    packages:
      - python-setuptools
      - libhdf5-serial-dev
      - pandoc
      - python-pygments
      - python3-pygments
      - nodejs

script:
  - pip install torch
  - python setup.py pytest
