dist: bionic
language: python

os:
  - linux

#python:
  #- 3.7

addons:
  apt:
    packages:
      - python-setuptools
      - libhdf5-serial-dev
      - pandoc
      - python-pygments
      - python3-pygments
      - nodejs
      - python3-pip
      - python3-setuptools
      - python3-pandas
      - python3-numpy
      - python3-scipy

script:
  - pip3 install xgboost
  - pip3 install torch
  - cd tests
  - sh download_test_data.sh
  - cd ..
  - python3 setup.py pytest
